development:
  adapter: postgresql
  encoding: unicode
  database: fin-goals_development
  pool: 5
  username: Matt
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fin-goals_test
  pool: 5
  username: Matt
  password:
    